export const employeesData = [
  {
    id: 1,
    name: "John Doe",
    role: "Admin",
    email: "john.doe@example.com",
    phone: "555-1234",
  },
  {
    id: 2,
    name: "Jane Smith",
    role: "Worker",
    email: "jane.smith@example.com",
    phone: "555-5678",
  },
  {
    id: 3,
    name: "Jim Brown",
    role: "Worker",
    email: "jim.brown@example.com",
    phone: "555-8765",
  },
  {
    id: 4,
    name: "Emily Johnson",
    role: "Admin",
    email: "emily.johnson@example.com",
    phone: "555-4321",
  },
  {
    id: 5,
    name: "Michael Davis",
    role: "Worker",
    email: "michael.davis@example.com",
    phone: "555-6789",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    role: "Admin",
    email: "sarah.wilson@example.com",
    phone: "555-8761",
  },
  {
    id: 7,
    name: "David Martinez",
    role: "Worker",
    email: "david.martinez@example.com",
    phone: "555-1235",
  },
  {
    id: 8,
    name: "Laura Garcia",
    role: "Admin",
    email: "laura.garcia@example.com",
    phone: "555-5679",
  },
  {
    id: 9,
    name: "Robert Rodriguez",
    role: "Worker",
    email: "robert.rodriguez@example.com",
    phone: "555-8766",
  },
  {
    id: 10,
    name: "Linda Martinez",
    role: "Admin",
    email: "linda.martinez@example.com",
    phone: "555-4322",
  },
  {
    id: 11,
    name: "James Hernandez",
    role: "Worker",
    email: "james.hernandez@example.com",
    phone: "555-6780",
  },
  {
    id: 12,
    name: "Patricia Lopez",
    role: "Admin",
    email: "patricia.lopez@example.com",
    phone: "555-8762",
  },
  {
    id: 13,
    name: "Charles Harris",
    role: "Worker",
    email: "charles.harris@example.com",
    phone: "555-1236",
  },
  {
    id: 14,
    name: "Barbara Clark",
    role: "Admin",
    email: "barbara.clark@example.com",
    phone: "555-5680",
  },
  {
    id: 15,
    name: "Paul Lewis",
    role: "Worker",
    email: "paul.lewis@example.com",
    phone: "555-8767",
  },
  {
    id: 16,
    name: "Nancy Young",
    role: "Admin",
    email: "nancy.young@example.com",
    phone: "555-4323",
  },
  {
    id: 17,
    name: "Steven Hall",
    role: "Worker",
    email: "steven.hall@example.com",
    phone: "555-6781",
  },
  {
    id: 18,
    name: "Karen Allen",
    role: "Admin",
    email: "karen.allen@example.com",
    phone: "555-8763",
  },
  {
    id: 19,
    name: "Matthew King",
    role: "Worker",
    email: "matthew.king@example.com",
    phone: "555-1237",
  },
  {
    id: 20,
    name: "Elizabeth Scott",
    role: "Admin",
    email: "elizabeth.scott@example.com",
    phone: "555-5681",
  },
];
